// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type {
  BylineSummary,
  ContentBylineCredit,
  TaxonomyTerm,
  PortableTextBlock,
  ReferencePage,
} from "emdash"

export interface Page {
  id: string
  slug: string | null
  status: string
  title: string
  content?: PortableTextBlock[]
  createdAt: Date
  updatedAt: Date
  publishedAt: Date | null
  byline?: BylineSummary | null
  bylines?: ContentBylineCredit[]
  terms?: Record<string, TaxonomyTerm[]>
}

export interface Post {
  id: string
  slug: string | null
  status: string
  title: string
  featured_image?: {
    id: string
    src?: string
    alt?: string
    width?: number
    height?: number
    filename?: string
    mimeType?: string
    blurhash?: string
    dominantColor?: string
    focalX?: number
    focalY?: number
    provider?: string
    previewUrl?: string
    meta?: Record<string, unknown>
    darkVariant?: {
      id: string
      src?: string
      alt?: string
      width?: number
      height?: number
      filename?: string
      mimeType?: string
      blurhash?: string
      dominantColor?: string
      focalX?: number
      focalY?: number
      provider?: string
      previewUrl?: string
      meta?: Record<string, unknown>
    }
  }
  content?: PortableTextBlock[]
  excerpt?: string
  createdAt: Date
  updatedAt: Date
  publishedAt: Date | null
  byline?: BylineSummary | null
  bylines?: ContentBylineCredit[]
  terms?: Record<string, TaxonomyTerm[]>
}

export interface Project {
  id: string
  slug: string | null
  status: string
  title: string
  description?: string
  featured_image?: {
    id: string
    src?: string
    alt?: string
    width?: number
    height?: number
    filename?: string
    mimeType?: string
    blurhash?: string
    dominantColor?: string
    focalX?: number
    focalY?: number
    provider?: string
    previewUrl?: string
    meta?: Record<string, unknown>
    darkVariant?: {
      id: string
      src?: string
      alt?: string
      width?: number
      height?: number
      filename?: string
      mimeType?: string
      blurhash?: string
      dominantColor?: string
      focalX?: number
      focalY?: number
      provider?: string
      previewUrl?: string
      meta?: Record<string, unknown>
    }
  }
  featured?: boolean
  link?: string
  github?: string
  content?: PortableTextBlock[]
  gallery?: {
    image?: {
      id: string
      src?: string
      alt?: string
      width?: number
      height?: number
      filename?: string
      mimeType?: string
      blurhash?: string
      dominantColor?: string
      focalX?: number
      focalY?: number
      provider?: string
      previewUrl?: string
      meta?: Record<string, unknown>
      darkVariant?: {
        id: string
        src?: string
        alt?: string
        width?: number
        height?: number
        filename?: string
        mimeType?: string
        blurhash?: string
        dominantColor?: string
        focalX?: number
        focalY?: number
        provider?: string
        previewUrl?: string
        meta?: Record<string, unknown>
      }
    } | null
  }[]
  createdAt: Date
  updatedAt: Date
  publishedAt: Date | null
  byline?: BylineSummary | null
  bylines?: ContentBylineCredit[]
  terms?: Record<string, TaxonomyTerm[]>
}

export interface PostReferences {
  projects: ReferencePage<Project>
}

export interface ProjectReferences {
  posts: ReferencePage<Post>
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page
    posts: Post
    projects: Project
  }
  interface EmDashCollectionReferences {
    posts: PostReferences
    projects: ProjectReferences
  }
}
